USE unhl405k407wjdze;
DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE USUARIOS (ID BIGINT NOT NULL AUTO_INCREMENT UNIQUE, NAME VARCHAR(255) NOT NULL, EMAIL VARCHAR(255) NOT NULL UNIQUE, PASSWORD VARCHAR(255) NOT NULL, PRIMARY KEY(ID));
SELECT * FROM USUARIOS;